// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZQT9BFAR8vNAgq1B_ZgjhSF8_YCYsDI',
    appId: '1:652253781483:web:e8bd9679f85f9314710dae',
    messagingSenderId: '652253781483',
    projectId: 'lumi-803c2',
    authDomain: 'lumi-803c2.firebaseapp.com',
    storageBucket: 'lumi-803c2.firebasestorage.app',
    measurementId: 'G-3KKXNV0TBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LgUUX411kVRbQW82cctiOO-3pGq2Adc',
    appId: '1:652253781483:android:17490468f99c60b2710dae',
    messagingSenderId: '652253781483',
    projectId: 'lumi-803c2',
    storageBucket: 'lumi-803c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJm9uPQ9y8Ik4NoeaTDRplNy7i1FY4CYw',
    appId: '1:652253781483:ios:cafd38f27ca1d8b5710dae',
    messagingSenderId: '652253781483',
    projectId: 'lumi-803c2',
    storageBucket: 'lumi-803c2.firebasestorage.app',
    iosBundleId: 'com.example.lumi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJm9uPQ9y8Ik4NoeaTDRplNy7i1FY4CYw',
    appId: '1:652253781483:ios:cafd38f27ca1d8b5710dae',
    messagingSenderId: '652253781483',
    projectId: 'lumi-803c2',
    storageBucket: 'lumi-803c2.firebasestorage.app',
    iosBundleId: 'com.example.lumi',
  );
}
